apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guestbook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: guestbook
subjects:
  - kind: ServiceAccount
    name: guest-guestbook
    namespace: default
