name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Check if Chart version has changed
        id: version_check
        run: |
          CHART_VERSION=$(yq eval '.version' ./charts/guestbook/Chart.yaml)
          echo "Detected Chart version: $CHART_VERSION"
          
          echo ${{ secrets.OCI_REGISTRY_PASSWORD }} | helm registry login -u ${{ secrets.OCI_REGISTRY_USERNAME }} --password-stdin images.neolink-ai.com

          # Check if this version exists in the remote OCI registry
          REGISTRY="images.neolink-ai.com/mocloud-charts/guestbook"
          VERSION_EXISTS=$(helm pull oci://$REGISTRY --version $CHART_VERSION --destination /tmp || echo "not found")
          if [[ "$VERSION_EXISTS" == "not found" ]]; then
            echo "New Chart version detected"
            echo "version_changed=true" >> $GITHUB_ENV
          else
            echo "Chart version already exists, skipping deployment"
            echo "version_changed=false" >> $GITHUB_ENV
          fi

      - name: Package Helm Chart
        if: env.version_changed == 'true'
        run: |
          helm package ./charts --destination ./package
          echo "Chart packaged successfully."

      - name: Push to OCI Registry
        if: env.version_changed == 'true'
        run: |
          helm push *.tgz oci://images.neolink-ai.com/mocloud-charts
