name: Release Helm Chart

on:
  push:
    paths:
      - 'charts/**/Chart.yaml'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0  # 选择一个适当的 Helm 版本

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Get chart version
        id: chart_version
        run: |
          CHART_VERSION=$(yq eval '.version' charts/*/Chart.yaml)
          echo "::set-output name=version::$CHART_VERSION"

      - name: Check if version changed
        id: version_changed
        run: |
          git fetch origin main
          PREVIOUS_VERSION=$(git show origin/main:charts/*/Chart.yaml | yq eval '.version' -)
          if [ "$PREVIOUS_VERSION" != "${{ steps.chart_version.outputs.version }}" ]; then
            echo "Version changed"
            echo "::set-output name=changed::true"
          else
            echo "Version did not change"
            echo "::set-output name=changed::false"
          fi

      - name: Package Helm Chart
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          helm package charts/*

      - name: Push to OCI Registry
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          echo ${{ secrets.OCI_REGISTRY_PASSWORD }} | helm registry login -u ${{ secrets.OCI_REGISTRY_USERNAME }} --password-stdin oci://images.neolink-ai.com
          helm push *.tgz oci://images.neolink-ai.com/mocloud-charts
